name: Repo Dates

# Declare default permissions as read only.
permissions: read-all

on:
  workflow_dispatch:
    inputs:
      github-org:
        type: choice
        description: Which org to check
        options:
        - hyperledger
        - hyperledger-labs
        required: true
      start-date:
        type: string
        description: Start date YYYY-MM-DD
        required: true

jobs:
  run-report:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
    - name: Set up Python 3.10
      uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        cd list-old-repos
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Old Repos
      run: |
        cd list-old-repos
        python main.py -t ${{ secrets.GITHUB_TOKEN }} -o ${{ inputs.github-org }} -d -w ${{ inputs.start-date }} | tee old-repos-${{ inputs.github-org }}-${{ inputs.start-date }}.csv
    - name: Upload reports
      uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
      with:
        # Artifact name
        name: old-repos-${{ inputs.github-org }}-${{ inputs.start-date }}
        # A file, directory or wildcard pattern that describes what to upload
        path: list-old-repos/*.csv
